dops

diff --git a/bin/do-git-clone b/bin/do-git-clone
--- a/bin/do-git-clone
+++ b/bin/do-git-clone
@@ -1,64 +1,28 @@
-#!/bin/sh
+#!/bin/bash
 
-zero="$(basename "$0")"
-usage(){
-  cat <<EOF
-$zero [-b BRANCH] [-k KEYFILE] [-s STAMPFILE] URL [DIR]
-EOF
-}
+: ${DOPS_BIN_DIR:="$(dirname "$(readlink -f "$0")")"}
+: ${DOPS_DIR:="$(cd "$DOPS_BIN_DIR/.."; pwd)"}
 
-abs(){
-  (
-    cd "$(dirname "$1")"
-    echo "$PWD/$(basename "$1")"
-  )
-}
+. "$DOPS_DIR/dopsh_functions.sh"
 
-branch=HEAD
-keyfile=
-stampfile=
+dopsh-init "$0" "$@"
+dopsh-parseopt "H:help -b= --branch=branch -k= --key=sshkey -s= --stamp=stampfile -u= --user= url [dir]" "$@" || exit 1
 
-while [ $# -gt 0 ]; do
-  case "$1" in
-    -h|--help|help)
-      usage >&2
-      exit 1
-      ;;
-    -b)
-      branch="$2"
-      shift 2
-      ;;
-    -k)
-      keyfile="`abs "$2"`"
-      shift 2
-      ;;
-    -s)
-      stampfile="`abs "$2"`"
-      shift 2
-      ;;
-    --)
-      shift
-      break
-      ;;
-    *)
-      break
-      ;;
-  esac
-done
+dopsh-opt       branch HEAD b
+dopsh-opt -file key    ""   k
+dopsh-opt -file stamp  ""   s
+dopsh-opt       user   ""   u
+dopsh-opt -file dir    "$(basename "$op_url")"
 
-url="$1"
-dir="$2"
+wrapgitop=()
 
-: ${dir:="$(basename "$url")"}
-
-if [ -z "$url" ]; then
-  echo "Missing URL" >&2
-  exit 1
+if [ -n "$user" ]; then
+  wrapgitop=("${wrapgitop[@]}" sudo -u "$op_user")
 fi
 
-if [ -n "$keyfile" ]; then
-  if ! [ -e "$keyfile" ]; then
-    echo "$keyfile: not found" >&2
+if [ -n "$op_key" ]; then
+  if ! [ -e "$op_key" ]; then
+    echo "$op_key: not found" >&2
     exit 10
   fi
 
@@ -66,35 +30,35 @@ if [ -n "$keyfile" ]; then
     do-install-file /usr/bin/gem
     gem install git-ssh-wrapper
   fi
-
-  wrapgit(){
-    git-ssh-wrapper "$keyfile" git "$@"
-    return $?
-  }
-else
-  wrapgit(){
-    git "$@"
-    return $?
-  }
+  
+  wrapgitop=("${wrapgitop[@]}" git-ssh-wrapper "$op_key")
 fi
 
+wrapgit(){
+  "${wrapgitop[@]}" git "$@"
+}
+
+[ 1 = "$REDO_XTRACE" ] && set -x
 set -e
 
-if [ -e "$dir/.git" ]; then
-  cd "$dir"
-  set -x
-  wrapgit fetch "$url" "$branch"
+if [ -e "$op_dir/.git" ]; then
+  cd "$op_dir"
+  wrapgit fetch "$op_url" "$op_branch"
   wrapgit reset --hard FETCH_HEAD
   wrapgit submodule update --init --recursive --force
-elif [ -e "$dir" ]; then
-  echo "$dir: already exists" >&2
+elif [ -e "$op_dir" ]; then
+  echo "$op_dir: already exists" >&2
   exit 11
 else
-  wrapgit clone --recursive "$url" "$dir"
-  cd "$dir"
+  if [ HEAD != "$op_branch" ]; then
+    wrapgit clone --recursive -b "$op_branch" "$op_url" "$op_dir"
+  else
+    wrapgit clone --recursive "$op_url" "$op_dir"
+  fi
+  cd "$op_dir"
 fi
 
-if [ -n "$stampfile" ]; then
-  git rev-parse HEAD >"$stampfile"
+if [ -n "$op_stamp" ]; then
+  git rev-parse HEAD >"$op_stamp"
 fi
 
diff --git a/bin/do-passwd b/bin/do-passwd
--- a/bin/do-passwd
+++ b/bin/do-passwd
@@ -1,61 +1,12 @@
-#!/bin/sh
+#!/bin/bash
 
-zero="$(basename "$0")"
-usage(){
-  cat <<EOF
-$zero declare-user [--shell SHELL] [--home HOMEDIR] USER
-EOF
-}
+: ${DOPS_BIN_DIR:="$(dirname "$(readlink -f "$0")")"}
+: ${DOPS_DIR:="$(cd "$DOPS_BIN_DIR/.."; pwd)"}
 
-warn(){
-  printf "$@" >&2
-}
+. "$DOPS_DIR/dopsh_functions.sh"
 
-has(){
-  which "$@" >/dev/null 2>&1
-}
-
-operation=help
-user=
-shell=
-home=
-login_group=
-
-while [ $# -gt 0 ]; do
-  case "$1" in
-    -h|--help|help)
-      usage >&2
-      exit 1
-      ;;
-    declare-user)
-      operation=declare-user
-      shift
-      ;;
-    --shell)
-      shell="$2"
-      shift 2
-      ;;
-    --home)
-      home="$2"
-      shift 2
-      ;;
-    --)
-      shift
-      break
-      ;;
-    *)
-      case $operation in
-        declare-user)
-          user="$1"
-          ;;
-        *)
-          warn "Unknown parameter %s\n" "$1"
-          ;;
-      esac
-      shift
-      ;;
-  esac
-done
+dopsh-init "$0" "$@"
+dopsh-parseopt "H:help command" "$@" || exit 1
 
 has_user(){
   cut -d: -f1 /etc/passwd | fgrep -x "$1" >/dev/null
@@ -66,57 +17,63 @@ has_group(){
 }
 
 declare_group(){
-  local group="$1"
-  if ! has_group "$group"; then
+  local op_group op_gid op
+  dopsh-parseopt "H:help -gid= group" "$@" || return 1
+
+  if ! has_group "$op_group"; then
     if has groupadd; then
-      ( set -x; groupadd "$group" )
+      op=()
+      [[ -n "$op_gid" ]] && op+=(--gid "$op_gid")
+      ( set -x; groupadd ${op[@]} "$op_group" )
       return $?
     else
-      warn "Cannot create group $group: Unknown platform"
-      return 1
+      fail "Cannot create group $op_group: Unknown platform"
     fi
   fi
 }
 
-case $operation in
-  declare-user)
-    if [ -z "$user" ]; then
-      warn "Missing username"
-      exit 1
-    fi
-    : ${login_group:="$user"}
-    if ! has_user "$user"; then
-      if has useradd; then
-        op="--create-home -g $login_group"
-        [ -n "$home"  ] && op+=" --home $home"
-        [ -n "$shell" ] && op+=" --shell $shell"
-        set -e
-        declare_group "$login_group"
-        ( set -x; useradd $op "$user" )
-      else
-        warn "Cannot create user: Unknown platform"
-        exit 1
-      fi
+declare_user(){
+  local op_uid op_name op_groups op_login_group op_shell op_home op_user
+  dopsh-parseopt "H:help -uid= -name= -groups= -login-group= -shell= -home= user" "${opts[@]}" || exit 1
+
+  : ${op_login_group:="$op_user"}
+
+  if has useradd && has usermod; then
+    local op
+    if ! has_user "$op_user"; then
+      op=(useradd --create-home -g "$op_login_group")
     else
-      if has usermod; then
-        op="--move-home -g $login_group"
-        [ -n "$home"  ] && op+=" --home $home"
-        [ -n "$shell" ] && op+=" --shell $shell"
-        set -e
-        declare_group "$login_group"
-        ( set -x; usermod $op "$user" )
-      else
-        warn "Cannot update user: Unknown platform"
-        exit 1
-      fi
+      op=(usermod --move-home -g "$op_login_group")
     fi
-    if [ -n "$home" ] && ! [ -e "$home" ]; then
-      ( set -x; install -o "$user" -g "$login_group" -m 0711 -d "$home" )
-    fi
+    [ -n "$op_home"  ]  && op+=(--home    "$op_home")
+    [ -n "$op_shell" ]  && op+=(--shell   "$op_shell")
+    [ -n "$op_uid" ]    && op+=(--uid     "$op_uid")
+    [ -n "$op_name" ]   && op+=(--comment "$op_name")
+    [ -n "$op_name" ]   && op+=(--comment "$op_name")
+    [ -n "$op_groups" ] && op+=(--groups  "$op_groups")
+    set -e
+    declare_group "$op_login_group"
+    ( set -x; "${op[@]}" "$op_user" )
+  else
+    fail "Cannot create user $op_user: Unknown platform"
+  fi
+
+  if [ -n "$op_home" ] && ! [ -e "$op_home" ]; then
+    ( set -x; install -o "$op_user" -g "$op_login_group" -m 0711 -d "$op_home" )
+  fi
+}
+
+case $op_command in
+  declare-user)
+    declare_user "${opts[@]}"
+    exit $?
+    ;;
+  declare-group)
+    declare_group "${opts[@]}"
+    exit $?
     ;;
   *)
-    usage >&2
-    exit 1
+    fail "Invalid command $op_command (must be one of: declare-user declare-group)"
     ;;
 esac
 
